
//GOORM
const constArr = {
	//LISTEN
	PROCESS_ENV_PORT: 3001,
	PROCESS_ENV_IP: null,
	
	//PAYPAL
	PAYPAL_REDIRECT_RETURN_URL: "",
	PAYPAL_CLIENT_ID: "",
	PAYPAL_CLIENT_SECRET: "",
	
	//CLOUDINARY
	CLOUDINARY_CLOUD_NAME: "",
	CLOUDINARY_API_KEY: "",
	CLOUDINARY_API_SECRET: "",
	
	//MONGODB
	MONGODB_CONNECT_PASSWORD: ""
}

// HEROKU
// const constArr = {
// 	//LISTEN
// 	PROCESS_ENV_PORT: process.env.PORT,
// 	PROCESS_ENV_IP: process.env.IP,
	
// 	//PAYPAL
// 	PAYPAL_REDIRECT_RETURN_URL: "",
// 	PAYPAL_CLIENT_ID: "",
// 	PAYPAL_CLIENT_SECRET: "",
	
// 	//CLOUDINARY
// 	CLOUDINARY_CLOUD_NAME: "",
// 	CLOUDINARY_API_KEY: "",
// 	CLOUDINARY_API_SECRET: "",
	
// 	//MONGODB
// 	MONGODB_CONNECT_PASSWORD: ""
// }
 
module.exports = constArr;
